#!/usr/bin/env python3
import subprocess

subprocess.call(["./setup.sh"])

with open("config.txt", 'r') as f:
    hoardPath = f.readline().strip()
    print(hoardPath)
    tcMallocPath = f.readline().strip()
    print(tcMallocPath)
    editTcMallocPath = f.readline().strip()
    print(editTcMallocPath)
    scallocPath = f.readline().strip()
    print(scallocPath)
    benchmarkPath = f.readline().strip()

fileList = ["cache-scratch.py"]#, "cache-thrash.py", "larson.py", "linux-scalability.py"]

for file in fileList:
    f = open(file,'r')
    filedata = f.read()
    f.close()

    filedata = filedata.replace("HOARD_PATH", hoardPath)
    filedata = filedata.replace("EDIT_TCMALLOC_PATH", editTcMallocPath)
    filedata = filedata.replace("TCMALLOC_PATH", tcMallocPath)
    filedata = filedata.replace("SCALLOC_PATH", scallocPath)
    filedata = filedata.replace("BENCHMARK_PATH", benchmarkPath)

    f = open(file,'w')
    f.write(filedata)
    f.close()

